In [2]:
def getSheetNames(excelfile):
    from pandas import ExcelFile
    return (ExcelFile(excelfile)).sheet_names

def readExcelSheet1(excelfile):
    from pandas import read_excel
    return (read_excel(excelfile)).values

def readExcelRange(excelfile, sheetname="Sheet1", startrow=1, endrow=1, startcol=1, endcol=1):
    from pandas import read_excel
    values = (read_excel(excelfile, sheetname, header=None)).values;
    return values[startrow - 1:endrow, startcol - 1:endcol]
 
 
 #adasda
def readExcel(excelfile, **args):
    if args:
        data = readExcelRange(excelfile, **args)
    else:
        data = readExcelSheet1(excelfile)
    if data.shape == (1, 1):
        return data[0, 0]
    elif (data.shape)[0] == 1:
        return data[0]
    else:
        return data
def writeExcelData(x, excelfile, sheetname, startrow, startcol, reshape=None):
    from pandas import DataFrame, ExcelWriter
    from openpyxl import load_workbook
    if reshape:
        df = DataFrame(x.reshape(-1, len(x)))
    else:
        df = DataFrame(x)
    book = load_workbook(excelfile)
    writer = ExcelWriter(excelfile, engine='openpyxl')
    writer.book = book
    writer.sheets = dict((ws.title, ws) for ws in book.worksheets)
    df.to_excel(writer, sheet_name=sheetname, startrow=startrow - 1, startcol=startcol - 1, header=False, index=False)
    writer.save()
    writer.close()


In [3]:
"""
step1
Set the number of histogram bins using Sturges’s Rule 𝐵=⌈(log_2⁡𝑁 )+1⌉ or other considerations. E.g. B=15. 
Here, 𝑁 refers to the number of samples in Class F or Class M, assumed to be equal. For simplicity, 
you may use the same number of bins for both the features.

"""
import numpy as np

print(np.log2(10))

excelfile = r"/Users/omerorhan/Desktop/UCSC/MachineLearning/Assignment_2_Data_and_Template.xlsx";
sheets = getSheetNames(excelfile);
sheets

data = readExcel(excelfile)
dataFemale = data[data[:, 0] == 'Female']
countFemale = len(dataFemale)
dataMale = (data[data[:, 0] == 'Male'])
countMale = len(dataMale)
BFemale = (np.log2(countFemale)) + 1
BMale = (np.log2(countMale)) + 1
ℎ_min = np.amin(data[:, 1]);
ℎ_max = np.amax(data[:, 1]);

𝑠_min = np.amin(data[:, 2]);
𝑠_max = np.amax(data[:, 2]);

writeExcelData([ℎ_min], excelfile, 'Female Histogram', 1, 2)
writeExcelData([ℎ_max], excelfile, 'Female Histogram', 2, 2)
writeExcelData([𝑠_min], excelfile, 'Female Histogram', 3, 2)
writeExcelData([𝑠_max], excelfile, 'Female Histogram', 4, 2)
writeExcelData([np.mean(data[:, 1])], excelfile, 'Bayesian', 1, 3)
writeExcelData([np.mean(data[:, 2])], excelfile, 'Bayesian', 1, 4)
writeExcelData([len(data[:, 2])], excelfile, 'Bayesian', 9, 3)

#ℎm_min = np.amin(dataMale[:,1]);
#ℎm_max = np.amax(dataMale[:,1]);

#𝑠m_min = np.amin(dataMale[:,2]);
#𝑠m_max = np.amax(dataMale[:,2]);
writeExcelData([ℎ_min], excelfile, 'Male Histogram', 1, 2)
writeExcelData([ℎ_max], excelfile, 'Male Histogram', 2, 2)
writeExcelData([𝑠_min], excelfile, 'Male Histogram', 3, 2)
writeExcelData([𝑠_max], excelfile, 'Male Histogram', 4, 2)
writeExcelData([np.mean(dataMale[:, 1])], excelfile, 'Bayesian', 2, 3)
writeExcelData([np.mean(dataMale[:, 2])], excelfile, 'Bayesian', 2, 4)
writeExcelData([len(dataMale[:, 2])], excelfile, 'Bayesian', 10, 3)
B = 7
def Apply1DHistogramClassifier(ℎ_min, ℎ_max, s_min, s_max, B, HH, T):
    #print(HH)
    '''
    For every feature vector {ℎ_𝑖,𝑠_𝑖 } pair belonging to the training set, do:
    Transform {ℎ_𝑖,𝑠_𝑖 } to row-column indices {𝑟,𝑐 } using
	𝑟=𝑅𝑂𝑈𝑁𝐷((𝐵−1)((ℎ_𝑖−ℎ_min)/(ℎ_max−ℎ_min )))
	𝑐=𝑅𝑂𝑈𝑁𝐷((𝐵−1)((𝑠_𝑖−𝑠_min)/(𝑠_max−𝑠_min )))
    If gender 𝑔_𝑖=𝐹, update 𝐻_𝐹 as 𝐻_𝐹 [𝑟,𝑐]=𝐻_𝐹 [𝑟,𝑐]+1. Otherwise, update 𝐻_𝑀 as 𝐻_𝑀 [𝑟,𝑐]=𝐻_𝑀 [𝑟,𝑐]+1.

    '''
    #(np.round(((B-1)*(HH[:,0]-ℎ_min)/(ℎ_max-ℎ_min))))
    H_F = np.zeros((B, B), dtype='int');
    H_M = np.zeros((B, B), dtype='int');
    r = np.clip((((B - 1) * (HH[:, 0] - ℎ_min) / (ℎ_max - ℎ_min))), 0, B - 1);
    c = np.clip((((B - 1) * (HH[:, 1] - s_min) / (s_max - s_min))), 0, B - 1);
    newnumbers = []
    for n in r:
        newnumbers.append(round(n))

    newnumbers = []
    r = newnumbers
    for n in c:
        newnumbers.append(round(n))
    c = newnumbers

    count = 0
    for gender in T:
        if gender == 'Female':
            𝐻_𝐹[𝑟, 𝑐] = 𝐻_𝐹[𝑟, 𝑐] + 1
        else:
            𝐻_M[𝑟, 𝑐] = 𝐻_M[𝑟, 𝑐] + 1
        count = count + 1

    return 𝐻_𝐹, H_M

#Apply1DHistogramClassifier(ℎ_min,ℎ_max,s_min,s_max,B,HH,T)

#print(H_F)


3.321928094887362


In [ ]:
'''    
    count = 0
    for gender in T:
        if gender == 'Female':
            𝐻_𝐹 [𝑟,𝑐]=𝐻_𝐹 [𝑟,𝑐]+1
        else:
            𝐻_M [𝑟,𝑐]=𝐻_M [𝑟,𝑐]+1
        count = count + 1
    print(𝐻_𝐹)
''' 

In [4]:
BFemale = (np.log2(countFemale)) + 1
BMale = (np.log2(countMale)) + 1

print(np.log2(countFemale))
print(BMale.round())
bins = str(BFemale.round()) + "X" + str(BFemale.round())
bins
writeExcelData([bins], excelfile, 'Female Histogram', 6, 2)
writeExcelData([bins], excelfile, 'Male Histogram', 6, 2)


6.475733430966398
7.0


In [5]:
'''
Assume that the data is given as 𝑋={{ℎ_0,𝑠_0 },{ℎ_1,𝑠_1 },{ℎ_2,𝑠_2 },…,{ℎ_(𝑁−1),𝑠_(𝑁−1) }} 
where the heights are ℎ_𝑖, the handspans are 𝑠_𝑖 and the genders are given as G={𝑔_0,𝑔_1,𝑔_2,𝑔_3,…,𝑔_(𝑁−1) }.

'''

T = np.array([str(g) for g in data[:, 0]])
HH = data[:, 1:3]


In [6]:
'''
Construct separate 2D histograms for the two classes. One way to do this is to first initialize (with zeros) 
two matrices 𝐻_𝐹 and 𝐻_𝑀, each of size 𝐵×𝐵. Next, compute the minimum and maximum of each of the features 
found in the training data (irrespective of class). Let us call these limits ℎ_min, ℎ_max, 𝑠_min, and 𝑠_max. 
The matrices 𝐻_𝐹 and 𝐻_𝑀 will now be subjected to a sequence of updating operations till the histograms are built 
up.
'''

H_F = np.zeros((B, B))
H_M = np.zeros((B, B))

ℎ_min = np.amin(HH[:, 0]);
ℎ_max = np.amax(HH[:, 0]);

𝑠_min = np.amin(HH[:, 1]);
𝑠_max = np.amax(HH[:, 1]);

r = (((B - 1) * (HH[:, 0] - ℎ_min) / (ℎ_max - ℎ_min)).astype(float).round()).astype('int32');
c = (((B - 1) * (HH[:, 1] - s_min) / (s_max - s_min)).astype(float).round()).astype('int32');
zipped = zip(r, c)

for i, (r, c) in enumerate(zip(r, c)):
    """enumerate-->if we put array or list into it gives output with index/count i """
    if T[i] == 'Female':
        H_F[r, c] += 1;

    else:
        H_M[r, c] += 1;
'''
for i,b in enumerate(r):
    if T[i]=='Female':
        𝐻_𝐹[c[i],r[i]]=𝐻_𝐹 [c[i],r[i]]+1
    else:
        𝐻_M[c[i],r[i]]=𝐻_M[c[i],r[i]]+1
'''
writeExcelData(𝐻_𝐹, excelfile, 'Female Histogram', 7, 2)
writeExcelData(𝐻_M, excelfile, 'Male Histogram', 7, 2)
print(𝐻_𝐹)
print(𝐻_𝐹[1, 1])


[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  5.  4.  3.  0.  0.  0.]
 [ 1.  2. 16. 13.  1.  0.  0.]
 [ 0.  1. 12. 24.  2.  0.  0.]
 [ 0.  0.  2.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
5.0


In [7]:
#(Height, HandSpan, Gender, 7, height_min, height_max, handspan_min,
#                                                handspan_max)

#
def Build2DHistogramClassifier_2(X1, X2, T, B, x1min, x1max, x2min, x2max):
    HF = np.zeros((B, B), dtype='int');
    HM = np.zeros((B, B), dtype='int');
    bin_row_indices = ((((B - 1) * (X1 - x1min) / (x1max - x1min))).astype(float).round()).astype('int32');
    """this logic decides which bin the value goes into"""
    bin_column_indices = ((((B - 1) * (X2 - x2min) / (x2max - x2min))).astype(float).round()).astype('int32');
    """np.round-->applies the formula to all the values in the array"""
    zipped = zip(bin_row_indices, bin_column_indices)
    for i, (r, c) in enumerate(zip(bin_row_indices, bin_column_indices)):
        """enumerate-->if we put array or list into it gives output with index/count i """
        if T[i] == 'Female':
            HF[r, c] += 1;

        else:
            HM[r, c] += 1;
    return [HF, HM, zipped]

HF, HM, zipped = Build2DHistogramClassifier_2(HH[:, 0], HH[:, 1], T, 7, np.float64(ℎ_min), np.float64(ℎ_max),
                                              np.float64(s_min), np.float64(s_max))


In [8]:
'''
Separate the data into male and female subsets
Find the mean vector and the covariance matrix separately for males and females. You may use a built-in 
function to compute these parameters.
'''
female_matrix = np.column_stack((dataFemale[:, 1].astype(float), dataFemale[:, 2].astype(float)))
female_cov = np.cov(female_matrix, rowvar=False)
male_matrix = np.column_stack((dataMale[:, 1].astype(float), dataMale[:, 2].astype(float)))
male_cov = np.cov(male_matrix, rowvar=False)

writeExcelData(female_cov, excelfile, 'Bayesian', 4, 3)
writeExcelData(male_cov, excelfile, 'Bayesian', 6, 3)


In [9]:
from pandas import DataFrame, ExcelWriter

def Histogram(queries):
    parr = []
    genarr = []

    for query in queries:
        r = ((B - 1) * (query[0] - ℎ_min) / (ℎ_max - ℎ_min)).round()
        c = ((B - 1) * (query[1] - s_min) / (s_max - s_min)).round()

        countfemale = H_F[r.astype(int), c.astype(int)]
        countmale = H_M[r.astype(int), c.astype(int)]
        print(countfemale)
        print(countmale)
        probfemale = countfemale / (countfemale + countmale)
        probmale = countmale / (countfemale + countmale)
        print(probfemale)
        print(probmale)
        if probfemale > probmale:
            parr.append(probfemale)
            genarr.append("Female")
        else:
            parr.append(probmale)
            genarr.append("Male")

    parr = np.asarray(parr)
    #parr= parr.reshape((4,1))
    genarr = np.asarray(genarr)
    #genarr= genarr.reshape((4,1))
    writeExcelData(genarr, excelfile, 'Queries', 3, 3)
    writeExcelData(parr, excelfile, 'Queries', 3, 4)


queries = np.array([[69, 17.5], [66, 22], [70, 21.5], [69, 23.5]])
Histogram(queries)


1.0
1.0
0.5
0.5
2.0
11.0
0.15384615384615385
0.8461538461538461
2.0
10.0
0.16666666666666666
0.8333333333333334
0.0
1.0
0.0
1.0


In [10]:
"""

use another solution
For each requested query (height-handspan vector 𝒙={ℎ,𝑠}) compute the posterior probabilities
𝑝(𝐹|𝒙)=(𝑁_𝐹 (1/(2𝜋〖 |Σ_𝐹 |〗^(1/2) ) 𝑒^(−1/2 (𝒙−𝝁_𝑭 )  〖Σ_𝐹〗^(−1) (𝒙−𝝁_𝑭 )^𝑇 ) ))/((𝑁_𝑀 (1/(2𝜋〖 |Σ_𝑀 |〗^(1/2) ) 𝑒^(−1/2 (𝒙−𝝁_𝑴 )  〖Σ_𝑀〗^(−1) (𝒙−𝝁_𝑴 )^𝑇 ) ))+(𝑁_𝐹 (1/(2𝜋〖 |Σ_𝐹 |〗^(1/2) ) 𝑒^(−1/2 (𝒙−𝝁_𝑭 )  〖Σ_𝐹〗^(−1) (𝒙−𝝁_𝑭 )^𝑇 ) )) )
𝑝(𝑀|𝒙)=(𝑁_𝑀 (1/(2𝜋〖 |Σ_𝑀 |〗^(1/2) ) 𝑒^(−1/2 (𝒙−𝝁_𝑴 )  〖Σ_𝑀〗^(−1) (𝒙−𝝁_𝑴 )^𝑇 ) ))/((𝑁_𝑀 (1/(2𝜋〖 |Σ_𝑀 |〗^(1/2) ) 𝑒^(−1/2 (𝒙−𝝁_𝑴 )  〖Σ_𝑀〗^(−1) (𝒙−𝝁_𝑴 )^𝑇 ) ))+(𝑁_𝐹 (1/(2𝜋〖 |Σ_𝐹 |〗^(1/2) ) 𝑒^(−1/2 (𝒙−𝝁_𝑭 )  〖Σ_𝐹〗^(−1) (𝒙−𝝁_𝑭 )^𝑇 ) )) )
See “Calculation of the PDF of the binormal distribution” for hints on computing the shaded quantities.
Perform classification by comparing 𝑝(𝐹|𝒙) and 𝑝(𝑀|𝒙).
"""
import math
from numpy.linalg import inv, det

def calculateProbability(x, mean, cov):
    z = (x - mean)
    exponent = math.exp(-1 / 2 * (
                z[0][0] * z[0][0] * inv(cov)[0][0] + 2 * inv(cov)[0][1] * z[0][0] * z[0][1] + z[0][1] * z[0][1] *
                inv(cov)[1][1]))
    return ((1 / ((2 * math.pi) * math.sqrt(det(cov)))) * exponent)

female_mean = np.column_stack((np.mean(dataFemale[:, 1].astype(float)), np.mean(dataFemale[:, 2].astype(float))))
male_mean = np.column_stack((np.mean(dataMale[:, 1].astype(float)), np.mean(dataMale[:, 2].astype(float))))
resultlabel1 = []
problabel = []
queries = np.array([[69, 17.5], [66, 22], [70, 21.5], [69, 23.5]])
for query in queries:
    probfemale = calculateProbability(query, female_mean, female_cov)
    print(probfemale)
    probmale = calculateProbability(query, male_mean, male_cov)
    if probmale > probfemale:
        resultlabel1.append('Male')
        problabel.append(probmale)
    else:
        resultlabel1.append('Female')
        problabel.append(probfemale)

writeExcelData(resultlabel1, excelfile, 'Queries', 3, 5)
writeExcelData(problabel, excelfile, 'Queries', 3, 6)


0.0009801188065675529
0.007801161924853705
0.008519181576749364
0.0006365602102161147


In [11]:
def get_count_by_bayesian(target_array, height_array, handspan_array):
    mean_height = height_array.mean()
    mean_handspan = handspan_array.mean()
    cov_array = np.vstack([height_array, handspan_array])
    cov_matrix = np.cov(cov_array.astype(float), bias=False)
    diff_array = np.array([[target_array[0] - mean_height, target_array[1] - mean_handspan]])
    exp_num = np.exp(-(np.matmul(np.matmul(diff_array, np.linalg.inv(cov_matrix)), diff_array.T) / 2))
    estimated_count = len(height_array) * (1 / ((2 * math.pi) * math.sqrt(np.linalg.det(cov_matrix))) * exp_num)
    return estimated_count


In [17]:
queries = np.array([[69, 17.5], [66, 22], [70, 21.5], [69, 23.5]])

resultlabel1 = []
problabel = []
for query in queries:
    countfemale = get_count_by_bayesian(query, dataFemale[:, 1], dataFemale[:, 2])
    countmale = get_count_by_bayesian(query, dataMale[:, 1], dataMale[:, 2])
    if countmale[0][0] > countfemale[0][0]:
        resultlabel1.append('Male')
        problabel.append(countmale[0][0] / (countmale[0][0] + countfemale[0][0]))
    else:
        resultlabel1.append('Female')
        problabel.append(countfemale[0][0] / (countmale[0][0] + countfemale[0][0]))

writeExcelData(resultlabel1, excelfile, 'Queries', 3, 5)
writeExcelData(problabel, excelfile, 'Queries', 3, 6)




In [18]:
H_F = np.zeros((B, B))
H_M = np.zeros((B, B))

ℎ_min = np.amin(HH[:, 0]);
ℎ_max = np.amax(HH[:, 0]);

𝑠_min = np.amin(HH[:, 1]);
𝑠_max = np.amax(HH[:, 1]);

r = (((B - 1) * (HH[:, 0] - ℎ_min) / (ℎ_max - ℎ_min)).astype(float).round()).astype('int32');
c = (((B - 1) * (HH[:, 1] - s_min) / (s_max - s_min)).astype(float).round()).astype('int32');
zipped = zip(r, c)

for i, (r, c) in enumerate(zip(r, c)):
    """enumerate-->if we put array or list into it gives output with index/count i """



In [14]:
queries = np.array([[69, 17.5], [66, 22], [70, 21.5], [69, 23.5]])

resultlabel1 = []
problabel = []
for query in dataFemale:
    countfemale = get_count_by_bayesian(query, dataFemale[:, 1], dataFemale[:, 2])
    countmale = get_count_by_bayesian(query, dataMale[:, 1], dataMale[:, 2])
    if countmale[0][0] > countfemale[0][0]:
        resultlabel1.append('Male')
        problabel.append(countmale[0][0] / (countmale[0][0] + countfemale[0][0]))
    else:
        resultlabel1.append('Female')
        problabel.append(countfemale[0][0] / (countmale[0][0] + countfemale[0][0]))


TypeError: unsupported operand type(s) for -: 'str' and 'float'

In [62]:
def write_histogram_by_bayesian_excel(excel_file, sheet_name, BINS, height_array, handspan_array, 
                                      min_height, max_height, min_handspan, max_handspan):

    histogram_data = np.zeros((BINS, BINS), dtype='int32')

    # get scale that one cell has.
    constant_height = (max_height-min_height)/(BINS)
    constant_handspan = (max_handspan-min_handspan)/(BINS)

    for i in range(BINS):
        for j in range(BINS):
            # calculate query of average height and handspan in the cell in the loop
            query_avg = np.array([min_height+(((i*constant_height)+(i*constant_height+constant_height))/2),
                                min_handspan+(((j*constant_handspan)+(j*constant_handspan+constant_handspan))/2)])

            # get count by Bayes classifier by using average height and handspan in the cell
            count_bayes_avg = get_count_by_bayesian(query_avg, height_array, handspan_array).item()

            # get count in the cell that has square, so multiply height and handspan
            count_bayes = count_bayes_avg*constant_height*constant_handspan

            # write the count to Excel. the count is rounded up in decimal point 3rd place.
            histogram_data[i][j]= np.round(count_bayes, 3)
    return histogram_data
            

In [60]:
def get_count_by_bayesian(target_array, height_array, handspan_array):
    mean_height = height_array.mean()
    mean_handspan = handspan_array.mean()

    cov_array = np.vstack([height_array, handspan_array])

    # get Covariance Matrix. bias=False means to get Unbiased Covariance
    cov_matrix = np.cov(cov_array.astype(float), bias=False)

    diff_array = np.array([[target_array[0]-mean_height, target_array[1]-mean_handspan]])

    # get estimated count
    exp_num = np.exp(-(np.matmul(np.matmul(diff_array, np.linalg.inv(cov_matrix)), diff_array.T)/2))
    estimated_count = len(height_array) * (1 / ((2 * math.pi) * math.sqrt(np.linalg.det(cov_matrix))) * exp_num)
    
    return estimated_count

In [64]:
histogram_dataf = write_histogram_by_bayesian_excel(excelfile,"Reconstructed Female Histogram",7, 
                                  dataFemale[:, 1], dataFemale[:, 2],ℎ_min,ℎ_max,s_min,s_max)
print(histogram_dataf)
writeExcelData(histogram_dataf, excelfile, 'Reconstructed Female Histogram', 7, 2)

histogram_datam = write_histogram_by_bayesian_excel(excelfile,"Reconstructed Female Histogram",7, 
                                  dataMale[:, 1], dataMale[:, 2],ℎ_min,ℎ_max,s_min,s_max)
print(histogram_datam)

writeExcelData(histogram_datam, excelfile, 'Reconstructed Male Histogram', 7, 2)


[[ 0  0  0  0  0  0  0]
 [ 1  5  6  1  0  0  0]
 [ 1  8 16  9  1  0  0]
 [ 0  2 10 10  2  0  0]
 [ 0  0  1  2  1  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]]


[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  1  4  4  1  0]
 [ 0  0  1  8 14  8  1]
 [ 0  0  0  2  8  9  3]
 [ 0  0  0  0  1  2  1]]
